name: dplpy4
channels:
  - conda-forge
  - defaults
dependencies:
  - bs4
  - pandas
  - matplotlib
  - wget
  - statsmodels
  - numpy
  - scipy
  - gfortran
  - jupyterlab
  - jupyter_contrib_nbextensions